-- Database schema for ASP.NET Core Identity (AppIdentityDbContext)
-- Provider: PostgreSQL
-- Tables: users, roles, user_roles, user_claims, role_claims, user_logins, user_tokens

CREATE TABLE IF NOT EXISTS roles (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    "Description" character varying(256),
    CONSTRAINT "PK_roles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS users (
    "Id" uuid NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL DEFAULT FALSE,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL DEFAULT FALSE,
    "AccessFailedCount" integer NOT NULL DEFAULT 0,
    "DisplayName" character varying(200),
    tenant_id uuid,
    person_id uuid,
    is_platform_admin boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS role_claims (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_role_claims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_role_claims_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_claims (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_user_claims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_user_claims_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_logins (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_user_logins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_user_logins_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_roles (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_user_roles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_user_roles_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_user_roles_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_tokens (
    "UserId" uuid NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_user_tokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_user_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

-- Indexes matching ASP.NET Identity defaults (unique indexes are filtered on NOT NULL)
CREATE UNIQUE INDEX IF NOT EXISTS "IX_roles_NormalizedName" ON roles ("NormalizedName") WHERE "NormalizedName" IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_NormalizedUserName" ON users ("NormalizedUserName") WHERE "NormalizedUserName" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_users_NormalizedEmail" ON users ("NormalizedEmail");
CREATE INDEX IF NOT EXISTS "IX_role_claims_RoleId" ON role_claims ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_user_claims_UserId" ON user_claims ("UserId");
CREATE INDEX IF NOT EXISTS "IX_user_logins_UserId" ON user_logins ("UserId");
CREATE INDEX IF NOT EXISTS "IX_user_roles_RoleId" ON user_roles ("RoleId");
